### ISSUE TITLE
Use default instead of else if

### ISSUE THREAD

**Issue by JensHeinrich** [martialblog/helm-charts#19]
As the value is needed, it seems it would be cleaner to use the [default function](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-default-function) instead of the if-else here

https://github.com/martialblog/helm-charts/blob/3226c71799a66f0c1edaafe5f117039b3f223803/limesurvey/templates/secrets.yaml#L13

Whats your opinion?

**Comment by martialblog** [comment]
Hm maybe... personally I'd avoid that anyways, it's just convenient for development I guess.

See also https://github.com/helm/charts/issues/5167#issuecomment-391217465 )

**Comment by martialblog** [comment]
We're keeping it as is for now. Should the need for refactoring arise, will look into it.
