### ISSUE TITLE
Feature Request: Replace the hard coded default secrets with autogenerated ones

### ISSUE THREAD

**Issue by JensHeinrich** [martialblog/helm-charts#20]
There is already a level of autogeneration of secrets, but there are still db passwords hardcoded in the configurations.
It seems to be easier to describe how to extract those from the cluster like in the [gitlab manual](https://docs.gitlab.com/charts/installation/deployment.html#initial-login) and have all of those autogenerated

**Comment by martialblog** [comment]
Yeah makes sense.

**Comment by martialblog** [comment]
Ok been looking into this. Since we use either the existing MariaDB Chart or and external DB we can't generate random strings here, since we don't control the mechanism that would set the password. 

What we could do is set the defaults to empty.
