### ISSUE TITLE
List Limesurvey Helm chart on Artifacthub.io

### ISSUE THREAD

**Issue by jacksgt** [martialblog/helm-charts#23]
To help with the discoverability of this awesome chart(s), we should add it to Artifacthub.io, which is a central registry for Helm charts from various sources.

You can sign up with your Github account on Artifacthub.io and then hit "Add Repository" on this page:
https://artifacthub.io/control-panel/repositories

P.S. I didn't want to steal your chart :-)

**Comment by martialblog** [comment]
https://artifacthub.io/packages/helm/martialblog/limesurvey

Tada :tada:
