### ISSUE TITLE
Heads-up: Bitnami repository "deprecation"

### ISSUE THREAD

**Issue by jacksgt** [martialblog/helm-charts#59]
Hey,

I'm not sure how much users of this chart are affected by it, but Bitnami just did a major blunder with their Helm repo: https://github.com/bitnami/charts/issues/10539

In essence, they decided to prune to all chart version older than six months from their index....

**Comment by martialblog** [comment]
I just merged https://github.com/martialblog/helm-charts/pull/58 which bumps the MariaDB Chart to v11 which is in their index.yaml
