### ISSUE TITLE
bump the new release

### ISSUE THREAD

**Issue by KelvinVenancio** [martialblog/helm-charts#76]
I would like to use [this feature](https://github.com/martialblog/helm-charts/commit/9f741ae968c57369e2d57d4408ee711693bc56a3), and I would like to know when you plan to bump the new chart version. Thank you.

**Comment by martialblog** [comment]
Sorry, totally missed that. I just bumped the version!

Thanks

**Comment by martialblog** [comment]
Fixed with https://github.com/martialblog/helm-charts/releases/tag/limesurvey-0.8.0
